### PR TITLE
Add archive-path autocomplete

### LINKED ISSUE #7: Design Idea: Read mod zip and Extract paths for selection
This one is definitely for after things are working.

Zip file paths are another common problem. It'd be neat to be able to scan a zip for a mod and allow building install stanzas from it. [jszip](https://stuk.github.io/jszip/)

### PR DESCRIPTION
**Pull request by janbrohl**
Closes #7

### CODE REVIEW

**Comment by janbrohl** [comment]
5962f0ad37d5aa2719165f450eda47e3e872104d does not suggest non-empty directories.
This is because extra entries are not needed for non-empty-directories and so are not included in the zip.

Edit: This seems to be wrong. jszip actually has the entries. Propably my testing data was badly chosen.

**Comment by janbrohl** [comment]
Split paths at "/" and add all directories to a set ( object keys?)

**Comment by mheguy** [comment]
can you toss together a build so I can test?

**Comment by janbrohl** [comment]
sure
[static.zip](https://github.com/KSP-CKAN/metadata-webtool/files/282619/static.zip)

bower_components should stay good for a while

**Comment by mheguy** [comment]
The only technical fault I see is that folders seem to generate 2 entries: `Folder` and `Folder/`

From a documentation side
My suggestion for lines 193 and 195 of index:
`Selecting the .zip file on your computer will enable automatic path completion.<br />`
`No data will be uploaded anywhere.`

I'd also like to see "Install path" changed as that usually describes where an install will end. I think just "Install" would be sufficient or "Install folder/file:"

**Comment by mheguy** [comment]
`as` isn't released yet.

**Comment by janbrohl** [comment]
"as" deactivated, spec version set accordingly

"as" depends on KSP-CKAN/CKAN/pull/1728 and release of v1.18

**Comment by janbrohl** [comment]
no negative echo in the last days - merging

**Pull request merged**
